# Generated by Django 2.2.7 on 2020-05-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
